### ISSUE TITLE
Questions about this module

### ISSUE THREAD

**Issue by wz2b** [wz2b/node-red-contrib-influxdb-line-protocol#1]
1. Do you have instructions on how to install this manually, as it doesn't seem to be in npm?
2. Do you have any interest in adding it to npm?
3. If you don't, do you mind if I fork it and contribute it to npm?
4. I think it would be simpler to make separate nodes for "line to json" and "json to line."  Doing what you did (where it dynamically transforms it from one to another) is clever but I think I'd rather be more explicit, and have it generate an error if the input message was in an unexpected format.  Would you be OK with this, and would you prefer I add or replace?

I'm looking for a few more options for creating line protocol messages.  The main addition I'm looking for is the ability to specify a static tag set in the node configuration.  I could do this by adding another node or by modifying one of the existing nodes.  My use case involves writing these messages to MQTT to be picked up by a telegraf instance somewhere else, which is what actually gets them to influxdb.  Telegraf can them route the message elsewhere if configured to do so.  So the basic, generic object model of "measurement tagset fieldset" makes sense even if the ultimate destination is sql, aws iot, prometheus, etc.  Because of that I'm interested in developing this module a little further.

Really, I'm going to go ahead with this on my own.  The main issue is I don't want to step on you by publishing this under the same name if you intended to do this yourself.  It looks like you haven't worked on this in a few years, if you've lost interest, I'll just take it over.

**Comment by opatut** [comment]
You need to delete or rename your fork, then I can transfer the repo (it won't be renamed so you need to have that URL free). Then I start the transfer and you need to accept it, I assume you get an email.

**Comment by opatut** [comment]
Cheers! :tada:

**Comment by wz2b** [comment]
Wow that was fast!

**Comment by wz2b** [comment]
Paul, did you ever put this into npm?  If you did I'll have to be named a
contributor to publish.

**Comment by wz2b** [comment]
disregard, it wasn't in npm.  I submitted it to npm and also to the node
red catalog, won't be bothering you now :-)
